{
  "openapi": "3.0.0",
  "info": {
    "title": "Marela API",
    "version": "1.0",
    "description": "Marela-Medifon tilaus API, Dev-vaiheessa "
  },
  "servers": [
    {
      "url": "https://api2.medifon.fi/api/marela/v1"
    }
  ],
  "paths": {
    "/{customercode}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get Customer",
        "tags": [
          "Customer"
        ],
        "operationId": "get-customers-cardcode",
        "description": "Palauttaa tiedot asiakkuudesta",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "customercode": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 15
                    },
                    "customername": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 100
                    },
                    "parentof": {
                      "type": "array",
                      "items": {
                        "$ref": "./Customer.v1.json"
                      }
                    }
                  },
                  "required": [
                    "customercode",
                    "customername"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "customercode": "00001",
                      "customername": "Apoteekki",
                      "parentof": [
                        {
                          "customercode": "00003",
                          "customername": "Apoteekki Robotti"
                        },
                        {
                          "customercode": "00001",
                          "customername": "Apoteekki Omakäyttö"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/{customercode}/orders": {
      "get": {
        "summary": "List Orders",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "./Order.v1.json"
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "orderno": 493289,
                        "customercode": "00001",
                        "customername": "Apteekki",
                        "orderdate": "2020-09-11T00:00:00",
                        "duedate": "2020-09-11T00:00:00",
                        "doctotalexvat": 1581.25,
                        "vatsum": 314.34,
                        "doctotal": 1895.59,
                        "reference": "47625",
                        "isbackorder": false,
                        "deliverywithnextorder": false,
                        "status": "O",
                        "orderrows": [
                          {
                            "itemcode": "9282974",
                            "description": "Ainoa B12-vitamiini 1mg 100 kaps",
                            "quantity": 2,
                            "pricebefdi": 10.9,
                            "discountpercent": 10,
                            "price": 9.81,
                            "vatpercent": 14,
                            "linetotal": 19.62,
                            "freetext": "",
                            "linestatus": "O"
                          },
                          {
                            "itemcode": "9282996",
                            "description": "Ainoa Kalsium + D3 100 kaps",
                            "quantity": 2,
                            "pricebefdi": 5.95,
                            "discountpercent": 10,
                            "price": 5.36,
                            "vatpercent": 14,
                            "linetotal": 10.71,
                            "freetext": "",
                            "linestatus": "O"
                          },
                          {
                            "itemcode": "9283018",
                            "description": "Ainoa Rauta 100mg + C 100 kaps",
                            "quantity": 2,
                            "pricebefdi": 9.95,
                            "discountpercent": 10,
                            "price": 8.96,
                            "vatpercent": 14,
                            "linetotal": 17.91,
                            "freetext": "",
                            "linestatus": "O"
                          },
                          {
                            "itemcode": "9236697",
                            "description": "Ainu sinkkivoide 100 ml",
                            "quantity": 1,
                            "pricebefdi": 2.04,
                            "discountpercent": 0,
                            "price": 2.04,
                            "vatpercent": 24,
                            "linetotal": 2.04,
                            "freetext": "",
                            "linestatus": "O"
                          },
                          {
                            "itemcode": "9238149",
                            "description": "Apteq B12 metyylikobalamiini 1000µg 30 tabl",
                            "quantity": 2,
                            "pricebefdi": 5.2,
                            "discountpercent": 20,
                            "price": 4.16,
                            "vatpercent": 14,
                            "linetotal": 8.32,
                            "freetext": "",
                            "linestatus": "O"
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "operationId": "get-orders",
        "description": "Palauttaa asiakkaan tilaukset",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "date",
              "example": "2020-01-01"
            },
            "in": "query",
            "name": "afterDate",
            "description": "Vain annettua päiväystä uudemmat tilaukset"
          },
          {
            "schema": {},
            "in": "query",
            "name": "onlyBackOrders",
            "description": "Vain jälkitoimitukseksi merkityt tilaukset"
          },
          {
            "schema": {},
            "in": "query",
            "name": "onlyOpenOrders",
            "description": "Vain avoimet tilaukset"
          },
          {
            "schema": {
              "type": "integer",
              "example": 16
            },
            "in": "query",
            "name": "customerOrderNo",
            "description": "Hae tilaus jonka customerorderno = ?"
          },
          {
            "schema": {
              "type": "string",
              "example": "12345"
            },
            "in": "query",
            "name": "orderNo",
            "description": "Hae tilaus jonka orderno = ?"
          }
        ],
        "tags": [
          "Orders"
        ]
      },
      "post": {
        "summary": "Create Order",
        "operationId": "post-orders",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "cardcode": {
                      "type": "string",
                      "description": "Medifonin asiakasnumero"
                    },
                    "cardname": {
                      "type": "string",
                      "description": "Asiakkaan nimi"
                    },
                    "lictradnum": {
                      "type": "string",
                      "description": "VAT-tunnus"
                    },
                    "reference": {
                      "type": "string",
                      "description": "Tilausviite"
                    },
                    "createdate": {
                      "type": "string",
                      "description": "Tilauksen luomispäivä",
                      "format": "date-time"
                    },
                    "docdate": {
                      "type": "string",
                      "description": "Tilauspäivä",
                      "format": "date-time"
                    },
                    "duedate": {
                      "type": "string",
                      "description": "Toimituspäivä",
                      "format": "date-time"
                    },
                    "deliverywithnextorder": {
                      "type": "boolean",
                      "description": "Toimitetaanko tilaus seuraavan tilauksen yhteydessä"
                    },
                    "status": {
                      "type": "string",
                      "description": "Tilauksen tila"
                    },
                    "orderrows": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "itemcode": {
                            "type": "string",
                            "description": "Medifonin tuotenumero"
                          },
                          "description": {
                            "type": "string",
                            "description": "Tuotteen kuvaus"
                          },
                          "quantity": {
                            "type": "integer",
                            "description": "Tilausmäärä"
                          },
                          "pricebefdi": {
                            "type": "number",
                            "description": "Alentamaton kappalehinta"
                          },
                          "discountpercent": {
                            "type": "number",
                            "description": "Alennus%"
                          },
                          "price": {
                            "type": "number",
                            "description": "Alennettu kappalehinta"
                          },
                          "status": {
                            "type": "string",
                            "description": "Tilausrivin tila"
                          },
                          "errorinfo": {
                            "type": "string",
                            "description": "Jos tilausivi on virheellinen palauttaa virheen"
                          }
                        },
                        "required": [
                          "itemcode",
                          "description",
                          "quantity",
                          "pricebefdi",
                          "discountpercent",
                          "price",
                          "errorinfo"
                        ]
                      }
                    }
                  },
                  "required": [
                    "cardcode",
                    "cardname",
                    "lictradnum",
                    "reference",
                    "createdate",
                    "docdate",
                    "deliverywithnextorder",
                    "orderrows"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "customerorderno": 72,
                      "customercode": "75490",
                      "customername": "Testiasiakas",
                      "reference": "kukkuluuruu",
                      "duedate": "2020-10-23T00:00:00",
                      "deliverywithnextorder": true,
                      "orderrows": [
                        {
                          "itemcode": "9236180",
                          "quantity": 10
                        },
                        {
                          "itemcode": "9248379",
                          "quantity": 10
                        },
                        {
                          "itemcode": "T121212",
                          "quantity": 10
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "description": "Luo asiakkaalle tilauksen",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "./OrderRequest.v1.json"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "customerorderno": 72,
                    "customercode": "75490",
                    "customername": "Testiasiakas",
                    "reference": "kukkuluuruu",
                    "duedate": "2020-10-23T00:00:00",
                    "deliverywithnextorder": true,
                    "orderrows": [
                      {
                        "itemcode": "9236180",
                        "quantity": 10
                      },
                      {
                        "itemcode": "9248379",
                        "quantity": 10
                      },
                      {
                        "itemcode": "T121212",
                        "quantity": 10
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Orders"
        ]
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ]
    },
    "/{customercode}/itemavailability": {
      "get": {
        "summary": "List Items & Availability",
        "tags": [
          "Items"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "./Item.v1.json"
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "itemcode": "T123456",
                        "itemname": "Testituote",
                        "onhand": 100,
                        "expirationdateonsale": null,
                        "availablefrom": null
                      },
                      {
                        "itemcode": "T654321",
                        "itemname": "Testituote erällä",
                        "onhand": 0,
                        "expirationdateonsale": null,
                        "availablefrom": "2025-01-12"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "operationId": "get-itemavailability",
        "description": "Palauttaa tuotteiden saatavuuden",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "000451, T121212"
            },
            "in": "query",
            "name": "itemcodes",
            "description": "Lista tarkastettavista tuotteista"
          },
          {
            "schema": {},
            "in": "query",
            "name": "onlyOutOfStockItems",
            "description": "Palauttaa vain tuotepuutteet"
          }
        ]
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ]
    },
    "/{customercode}/shipments": {
      "get": {
        "summary": "List Shipments",
        "tags": [
          "Shipments"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "./Shipment.v1.json"
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "shipmentid": 6907,
                        "customercode": "75490",
                        "receivername": "Testiasiakas",
                        "receiverstreet": "Kadunnimi 100",
                        "receivercity": "Helsinki",
                        "receiverzipcode": "00100",
                        "receivercountrycode": "FI",
                        "waybillnumber": 201022813320,
                        "datecreated": "2020-02-03T17:07:38.943",
                        "shipmentpacks": [
                          {
                            "packid": 18111,
                            "packtypename": "Medifon laatikko pieni palautettava",
                            "weight": 50,
                            "description": "Terveydenhuollon tuotteita",
                            "packno": 1,
                            "sscc": "00164382770726781117",
                            "packlines": [
                              {
                                "packlineid": 168175,
                                "linenumber": 1,
                                "itemcode": "T123456",
                                "description": "Testituote verkkokaupparuksi päällä",
                                "quantity": 1,
                                "quantityordered": 1,
                                "batch": "",
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 369949,
                                "reference": ""
                              }
                            ]
                          },
                          {
                            "packid": 18140,
                            "packtypename": "Medifon laatikko pieni palautettava",
                            "weight": 5,
                            "description": "Terveydenhuollon tuotteita",
                            "packno": 2,
                            "sscc": "00164382770729681407",
                            "packlines": [
                              {
                                "packlineid": 168484,
                                "linenumber": 1,
                                "itemcode": "T123456",
                                "description": "Testituote verkkokaupparuksi päällä",
                                "quantity": 2,
                                "quantityordered": 2,
                                "batch": "",
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 370032,
                                "reference": ""
                              }
                            ]
                          },
                          {
                            "packid": 18257,
                            "packtypename": "Medifon laatikko pieni palautettava",
                            "weight": 2,
                            "description": "Terveydenhuollon tuotteita",
                            "packno": 3,
                            "sscc": "00164382770735382572",
                            "packlines": [
                              {
                                "packlineid": 169715,
                                "linenumber": 5,
                                "itemcode": "T121212Z",
                                "description": "Testituote Kolli nollasaldo",
                                "quantity": 0,
                                "quantityordered": 3,
                                "batch": null,
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 370323,
                                "reference": ""
                              },
                              {
                                "packlineid": 169714,
                                "linenumber": 4,
                                "itemcode": "T123456",
                                "description": "Testituote verkkokaupparuksi päällä",
                                "quantity": 1,
                                "quantityordered": 1,
                                "batch": "",
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 370323,
                                "reference": ""
                              },
                              {
                                "packlineid": 169713,
                                "linenumber": 3,
                                "itemcode": "T123456",
                                "description": "Testituote verkkokaupparuksi päällä",
                                "quantity": 1,
                                "quantityordered": 1,
                                "batch": "",
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 370323,
                                "reference": ""
                              },
                              {
                                "packlineid": 169712,
                                "linenumber": 2,
                                "itemcode": "T123456",
                                "description": "Testituote verkkokaupparuksi päällä",
                                "quantity": 1,
                                "quantityordered": 1,
                                "batch": "",
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 370323,
                                "reference": ""
                              },
                              {
                                "packlineid": 169711,
                                "linenumber": 1,
                                "itemcode": "T123456",
                                "description": "Testituote verkkokaupparuksi päällä",
                                "quantity": 2,
                                "quantityordered": 2,
                                "batch": "",
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 370323,
                                "reference": ""
                              }
                            ]
                          },
                          {
                            "packid": 18273,
                            "packtypename": "Medifon laatikko pieni palautettava",
                            "weight": 2,
                            "description": "Terveydenhuollon tuotteita",
                            "packno": 4,
                            "sscc": "00164382770735482739",
                            "packlines": [
                              {
                                "packlineid": 169868,
                                "linenumber": 3,
                                "itemcode": "T121212Z",
                                "description": "Testituote Kolli nollasaldo",
                                "quantity": 0,
                                "quantityordered": 3,
                                "batch": "",
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 370377,
                                "reference": ""
                              },
                              {
                                "packlineid": 169867,
                                "linenumber": 2,
                                "itemcode": "T123456",
                                "description": "Testituote verkkokaupparuksi päällä",
                                "quantity": 0,
                                "quantityordered": 6,
                                "batch": "",
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 370377,
                                "reference": ""
                              },
                              {
                                "packlineid": 169866,
                                "linenumber": 1,
                                "itemcode": "T123456",
                                "description": "Testituote verkkokaupparuksi päällä",
                                "quantity": 2,
                                "quantityordered": 2,
                                "batch": "",
                                "expdate": null,
                                "unitpriceexvat": 0,
                                "discountpercent": 0,
                                "vatpercent": 0,
                                "orderno": 370377,
                                "reference": ""
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "operationId": "get-shipments",
        "description": "Palauttaa asiakkaan lähetykset"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ]
    },
    "/{customercode}/opencreditnotes": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get open Credit Notes",
        "tags": [
          "Credit Notes"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./CreditNote.v1.json"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "invoiceno": 0,
                      "customercode": "string",
                      "customername": "string",
                      "postingdate": "2019-08-24T14:15:22Z",
                      "duedate": "2019-08-24T14:15:22Z",
                      "taxdate": "2019-08-24T14:15:22Z",
                      "doctol": 0,
                      "openbalance": 0,
                      "vatsum": 0,
                      "paymentreference": "string",
                      "reference": "string",
                      "comments": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-customercode-opencreditnotes",
        "description": "Palauttaa asiakkaan avoimet hyvityslaskut"
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "apiKey": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "security": [
    {
      "apiKey": []
    }
  ],
  "tags": [
    {
      "name": "Credit Notes"
    }
  ]
}