{
  "openapi": "3.0.0",
  "info": {
    "title": "Pharmadata API",
    "version": "1.0",
    "description": "Geneerinen API Pharmadatan käyttöön"
  },
  "servers": [
    {
      "url": "http://medsrv04/PharmadataApi/api",
      "description": "Pharmadatan API"
    }
  ],
  "paths": {
    "/{customercode}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get Customer",
        "tags": [
          "Customer"
        ],
        "operationId": "get-customers-cardcode",
        "description": "Palauttaa tiedot asiakkuudesta",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "customercode": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 15
                    },
                    "customername": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 100
                    },
                    "parentof": {
                      "type": "array",
                      "items": {
                        "$ref": "./Customer.v1.json"
                      }
                    }
                  },
                  "required": [
                    "customercode",
                    "customername"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "customercode": "00001",
                      "customername": "Apoteekki",
                      "parentof": [
                        {
                          "customercode": "00003",
                          "customername": "Apoteekki Robotti"
                        },
                        {
                          "customercode": "00001",
                          "customername": "Apoteekki Omakäyttö"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/{customercode}/orders": {
      "get": {
        "summary": "List Orders",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "./Order.v1.json"
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "orderno": 493289,
                        "customercode": "00001",
                        "customername": "Apteekki",
                        "orderdate": "2020-09-11T00:00:00",
                        "duedate": "2020-09-11T00:00:00",
                        "doctotalexvat": 1581.25,
                        "vatsum": 314.34,
                        "doctotal": 1895.59,
                        "reference": "47625",
                        "isbackorder": false,
                        "deliverywithnextorder": false,
                        "status": "O",
                        "orderrows": [
                          {
                            "itemcode": "9282974",
                            "description": "Ainoa B12-vitamiini 1mg 100 kaps",
                            "quantity": 2,
                            "pricebefdi": 10.9,
                            "discountpercent": 10,
                            "price": 9.81,
                            "vatpercent": 14,
                            "linetotal": 19.62,
                            "freetext": "",
                            "linestatus": "O"
                          },
                          {
                            "itemcode": "9282996",
                            "description": "Ainoa Kalsium + D3 100 kaps",
                            "quantity": 2,
                            "pricebefdi": 5.95,
                            "discountpercent": 10,
                            "price": 5.36,
                            "vatpercent": 14,
                            "linetotal": 10.71,
                            "freetext": "",
                            "linestatus": "O"
                          },
                          {
                            "itemcode": "9283018",
                            "description": "Ainoa Rauta 100mg + C 100 kaps",
                            "quantity": 2,
                            "pricebefdi": 9.95,
                            "discountpercent": 10,
                            "price": 8.96,
                            "vatpercent": 14,
                            "linetotal": 17.91,
                            "freetext": "",
                            "linestatus": "O"
                          },
                          {
                            "itemcode": "9236697",
                            "description": "Ainu sinkkivoide 100 ml",
                            "quantity": 1,
                            "pricebefdi": 2.04,
                            "discountpercent": 0,
                            "price": 2.04,
                            "vatpercent": 24,
                            "linetotal": 2.04,
                            "freetext": "",
                            "linestatus": "O"
                          },
                          {
                            "itemcode": "9238149",
                            "description": "Apteq B12 metyylikobalamiini 1000µg 30 tabl",
                            "quantity": 2,
                            "pricebefdi": 5.2,
                            "discountpercent": 20,
                            "price": 4.16,
                            "vatpercent": 14,
                            "linetotal": 8.32,
                            "freetext": "",
                            "linestatus": "O"
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-orders",
        "description": "Palauttaa asiakkaan tilaukset",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "date",
              "example": "2020-01-01"
            },
            "in": "query",
            "name": "afterDate",
            "description": "Vain annettua päiväystä uudemmat tilaukset"
          },
          {
            "schema": {},
            "in": "query",
            "name": "onlyBackOrders",
            "description": "Vain jälkitilaukset"
          },
          {
            "schema": {},
            "in": "query",
            "name": "onlyOpenOrders",
            "description": "Vain avoimet tilaukset"
          }
        ],
        "tags": [
          "Orders"
        ]
      },
      "post": {
        "summary": "Create Order",
        "operationId": "post-orders",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "cardcode": {
                      "type": "string",
                      "description": "Medifonin asiakasnumero"
                    },
                    "cardname": {
                      "type": "string",
                      "description": "Asiakkaan nimi"
                    },
                    "lictradnum": {
                      "type": "string",
                      "description": "VAT-tunnus"
                    },
                    "reference": {
                      "type": "string",
                      "description": "Tilausviite"
                    },
                    "createdate": {
                      "type": "string",
                      "description": "Tilauksen luomispäivä",
                      "format": "date-time"
                    },
                    "docdate": {
                      "type": "string",
                      "description": "Tilauspäivä",
                      "format": "date-time"
                    },
                    "duedate": {
                      "type": "string",
                      "description": "Toimituspäivä",
                      "format": "date-time"
                    },
                    "deliverywithnextorder": {
                      "type": "boolean",
                      "description": "Toimitetaanko tilaus seuraavan tilauksen yhteydessä"
                    },
                    "status": {
                      "type": "string",
                      "description": "Tilauksen tila"
                    },
                    "orderrows": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "itemcode": {
                            "type": "string",
                            "description": "Medifonin tuotenumero"
                          },
                          "description": {
                            "type": "string",
                            "description": "Tuotteen kuvaus"
                          },
                          "quantity": {
                            "type": "integer",
                            "description": "Tilausmäärä"
                          },
                          "pricebefdi": {
                            "type": "number",
                            "description": "Alentamaton kappalehinta"
                          },
                          "discountpercent": {
                            "type": "number",
                            "description": "Alennus%"
                          },
                          "price": {
                            "type": "number",
                            "description": "Alennettu kappalehinta"
                          },
                          "status": {
                            "type": "string",
                            "description": "Tilausrivin tila"
                          },
                          "errorinfo": {
                            "type": "string",
                            "description": "Jos tilausivi on virheellinen palauttaa virheen"
                          }
                        },
                        "required": [
                          "itemcode",
                          "description",
                          "quantity",
                          "pricebefdi",
                          "discountpercent",
                          "price",
                          "errorinfo"
                        ]
                      }
                    }
                  },
                  "required": [
                    "cardcode",
                    "cardname",
                    "lictradnum",
                    "reference",
                    "createdate",
                    "docdate",
                    "deliverywithnextorder",
                    "orderrows"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "customerorderno": 71,
                      "customercode": "75490",
                      "customername": "Testiasiakas",
                      "orderdate": "2020-09-14T09:54:13.687",
                      "duedate": "2020-10-23T00:00:00",
                      "reference": "kukkuluuruu",
                      "deliverywithnextorder": true,
                      "status": "DRAFT",
                      "orderrows": [
                        {
                          "itemcode": "9236180",
                          "description": "Catapult Cat - Ravintolisä 16 x 6 tabl",
                          "quantity": 10,
                          "pricebefdi": 81.92,
                          "discountpercent": 0,
                          "price": 81.92,
                          "freetext": "",
                          "linestatus": "DRAFT"
                        },
                        {
                          "itemcode": "9248379",
                          "description": "APTEEKKI FluAcute Yskä 20 ml",
                          "quantity": 10,
                          "pricebefdi": 0,
                          "discountpercent": 0,
                          "price": 0,
                          "freetext": "",
                          "linestatus": "VALIDATIONERROR",
                          "errorinfo": "Tuotteen tilaaminen on sallittu vain Apteekkariliiton jäsenapteekeille"
                        },
                        {
                          "itemcode": "T121212",
                          "description": "Testituote Kolli",
                          "quantity": 10,
                          "pricebefdi": 0,
                          "discountpercent": 0,
                          "price": 0,
                          "freetext": "",
                          "linestatus": "VALIDATIONERROR",
                          "errorinfo": "Tuote ei ole jakelussa"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Luo asiakkaalle tilauksen",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "./OrderRequest.v1.json"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "customerorderno": 69,
                    "customercode": "75490",
                    "customername": "Testiasiakas",
                    "orderdate": "2020-09-14T09:45:11.24",
                    "duedate": "2020-10-23T00:00:00",
                    "reference": "kukkuluuruu",
                    "deliverywithnextorder": true,
                    "status": "DRAFT",
                    "orderrows": [
                      {
                        "itemcode": "T123456",
                        "description": "Testituote verkkokaupparuksi päällä",
                        "quantity": 10,
                        "pricebefdi": 0,
                        "discountpercent": 0,
                        "price": 0,
                        "freetext": "",
                        "linestatus": "VALIDATIONERROR",
                        "errorinfo": "Tuote ei ole jakelussa"
                      },
                      {
                        "itemcode": "T121212",
                        "description": "Testituote Kolli",
                        "quantity": 10,
                        "pricebefdi": 0,
                        "discountpercent": 0,
                        "price": 0,
                        "freetext": "",
                        "linestatus": "VALIDATIONERROR",
                        "errorinfo": "Tuote ei ole jakelussa"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Orders"
        ]
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ]
    },
    "/{customercode}/itemavailability": {
      "get": {
        "summary": "List Items Availability",
        "tags": [
          "Items"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "./Item.v1.json"
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "itemcode": "T123456",
                        "itemname": "Testituote",
                        "onhand": 100,
                        "expirationdateonsale": null,
                        "availablefrom": null
                      },
                      {
                        "itemcode": "T654321",
                        "itemname": "Testituote erällä",
                        "onhand": 0,
                        "expirationdateonsale": null,
                        "availablefrom": "2025-01-12"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "operationId": "get-itemavailability",
        "description": "Tuotteiden saatavuus",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "enum": [
                "true",
                "false"
              ],
              "example": "onlyOutOfStock=true"
            },
            "in": "query",
            "name": "onlyOutOfStockItems",
            "description": "Jos true niin palauttaa vain tuotteet joita ei varastossa"
          }
        ]
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ]
    },
    "/{customercode}/shipments": {
      "get": {
        "summary": "List Shipments",
        "tags": [
          "Shipments"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "./Shipment.v1.json"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "operationId": "get-shipments",
        "description": "Lähetykset asiakkaalle"
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ]
    },
    "/{customercode}/orders/{orderno}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "orderno",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "customercode",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get Order",
        "tags": [
          "Orders"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "./Order.v1.json"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "operationId": "get-customer-cardcode-orders-docnum",
        "description": "Palauttaa asiakkaan yksittäisen tilauksen"
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "apiKey": {
        "type": "http",
        "scheme": "basic"
      }
    }
  },
  "security": [
    {
      "apiKey": []
    }
  ]
}